In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("diabetes.csv")

In [3]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data.info()#basic idea that we get from the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
data.describe()#statistical analysis

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
# using isnull() function to see if any null data is available in the data set 
data.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

## Dividing the dataset into dependent and independent columns

In [7]:
X=data.drop(['Outcome'],axis=1) #independent features from the dataset
y=data['Outcome'] #dependent column from the dataset
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Splitting the dataset into training and testing set

### 20% of the dataset will be used for testing(evaluation) and 80% of the data will be used for training purposes

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# Linear Regression Algorithm

In [10]:
#creating the machine learning model
from sklearn.linear_model import LinearRegression
linearmodel=LinearRegression()
linearmodel.fit(X_train,y_train) # training is taking place

LinearRegression()

In [11]:
#predictions
linearmodel.predict(X_test)

array([ 0.25952727,  0.02538789,  0.49806502, -0.00391137,  0.24781237,
        0.27645541,  0.25251908,  0.16882985,  0.44142092,  0.18642435,
        0.25198827,  0.09083212,  0.55369137,  0.1654497 , -0.0625669 ,
        0.25758756,  0.60581484,  0.63598255,  0.8415336 ,  0.24878593,
        0.95674303,  0.40403195,  0.49855044,  0.75031781,  0.1159695 ,
        0.31652375,  0.42193704,  0.6753194 ,  0.11666345,  0.5860701 ,
        0.48706061,  0.46291619,  0.10388314,  0.34817992, -0.14988601,
        0.07962111, -0.02967156,  0.68217967,  0.57319168,  0.40529868,
        0.15021261,  0.81529827,  0.35943098,  0.43705889,  0.0198071 ,
        0.53972121,  0.67729711,  0.5308316 ,  0.42394467,  0.42539625,
        0.25931626,  0.5281196 ,  0.26199527,  0.07695315,  0.2659925 ,
        0.30529313, -0.13418178,  0.24092824,  0.72443282,  0.31637134,
        0.68205773,  0.4578575 ,  0.04995301,  0.39258015,  0.60215542,
        0.51141264,  0.69310734,  0.28366986,  0.99000445,  0.34

In [12]:
#calculating the accuracy of the model
linearmodel.score(X,y) # evaluation is taking place

0.3026573892059874

# Logistic Regression Algorithm

In [13]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [14]:
logmodel.fit(X_train,y_train)

C:\Users\aravindv\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
y_pred=logmodel.predict(X_test)

In [16]:
print(y_pred)

[0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0
 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0
 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0
 1 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [17]:
#calculating accuracy of the Classification model
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [18]:
print(cm)

[[95  6]
 [24 29]]


In [19]:
print(ac)

0.8051948051948052


# Decision Tree Algorithm

In [20]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [21]:
tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
predictions=tree_classifier.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [24]:
print(cm)

[[83 18]
 [22 31]]


In [25]:
print(ac)

0.7402597402597403


# KNN Algorithm

In [26]:
#importing KNN Classfier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=11)

In [27]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [28]:
predictions=knn.predict(X_test)

In [29]:
#accuracy
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [30]:
print(cm)

[[90 11]
 [25 28]]


In [31]:
print(ac)

0.7662337662337663


# Random Forest Algorithm

In [32]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [33]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [34]:
y_pred=classifier.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [36]:
print(cm)

[[92  9]
 [24 29]]


In [37]:
print(ac)

0.7857142857142857


# Support Vector Machine Algorithm

In [38]:
from sklearn.svm import SVC
svc_model=SVC()

In [39]:
svc_model.fit(X_train,y_train)

SVC()

In [40]:
predictions=svc_model.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [42]:
print(cm)

[[91 10]
 [28 25]]


In [43]:
print(ac)

0.7532467532467533
