NUMPY

In [ ]:
import numpy as np #np is the alias name

In [ ]:
my_list=[1,2,3,4,5]

In [ ]:
type(my_list)

list

In [ ]:
arr=np.array(my_list)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#multinested array
my_list=[1,2,3,4,5]
my_list_2=[4,5,3,5,7]
my_list_3=[3,4,5,1,2]

In [ ]:
arr_new=np.array([my_list,my_list_2,my_list_3])

In [ ]:
print(arr_new)

[[1 2 3 4 5]
 [4 5 3 5 7]
 [3 4 5 1 2]]


In [ ]:
arr_new.shape

(3, 5)

In [ ]:
arr_new.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [5, 3, 5],
       [7, 3, 4],
       [5, 1, 2]])

In [ ]:
#generating random numbers 

In [ ]:
arr=np.arange(0,10,1)

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
np.linspace(0,10,600) #600 means that in between the range i will get 50 unique values

array([ 0.        ,  0.01669449,  0.03338898,  0.05008347,  0.06677796,
        0.08347245,  0.10016694,  0.11686144,  0.13355593,  0.15025042,
        0.16694491,  0.1836394 ,  0.20033389,  0.21702838,  0.23372287,
        0.25041736,  0.26711185,  0.28380634,  0.30050083,  0.31719533,
        0.33388982,  0.35058431,  0.3672788 ,  0.38397329,  0.40066778,
        0.41736227,  0.43405676,  0.45075125,  0.46744574,  0.48414023,
        0.50083472,  0.51752922,  0.53422371,  0.5509182 ,  0.56761269,
        0.58430718,  0.60100167,  0.61769616,  0.63439065,  0.65108514,
        0.66777963,  0.68447412,  0.70116861,  0.71786311,  0.7345576 ,
        0.75125209,  0.76794658,  0.78464107,  0.80133556,  0.81803005,
        0.83472454,  0.85141903,  0.86811352,  0.88480801,  0.9015025 ,
        0.91819699,  0.93489149,  0.95158598,  0.96828047,  0.98497496,
        1.00166945,  1.01836394,  1.03505843,  1.05175292,  1.06844741,
        1.0851419 ,  1.10183639,  1.11853088,  1.13522538,  1.15

In [ ]:
np.random.rand(3,4)#3 is the number of rows and 4 is the number of columns
#default range is 0-->1
#the numbers in the array will change randomly everytime we run the cell

array([[0.75810564, 0.47577389, 0.15807698, 0.95759364],
       [0.1646917 , 0.7441578 , 0.15687477, 0.23409529],
       [0.69724435, 0.77789271, 0.84738116, 0.53025515]])

In [ ]:
np.random.randint(1,20,30) #30 denotes the number of random values that we get in the specifed range of 1-20
#the numbers in the array will change randomly everytime we run the cell

array([ 6, 10, 19, 18,  2,  4, 19,  1, 12, 14,  8,  8, 14,  3, 18,  9, 14,
        5, 13, 17, 11, 13,  5,  4, 13, 13,  3, 12,  6, 16])

PANDAS

In [6]:
import pandas as pd

In [7]:
#reading a dataset
data=pd.read_csv("/content/tips.csv")

In [8]:
data.head()#shows the first 5 rows of the dataset

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
data.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [10]:
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [12]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [13]:
#create your own dataset

In [17]:
import numpy as np

In [18]:
my_data=pd.DataFrame(np.arange(0,20).reshape(5,4), index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])

In [19]:
print(my_data)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [20]:
my_data.to_csv('sunday_demo_file.csv')

In [21]:
my_data.to_excel('sunday_demo_file.xlsx')

In [21]:
#.loc()
#.iloc()

In [23]:
print(my_data)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [25]:
my_data.iloc[2:4,2:]

col3  col4
row3    10    11
row4    14    15

In [26]:
my_data

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [27]:
my_data.iloc[0:3,0:2]

col1  col2
row1     0     1
row2     4     5
row3     8     9