In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/BankNoteAuthentication.csv")

In [3]:
data.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
X=data.drop(['class'],axis=1)
y=data['class']

In [5]:
X.head()

variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [6]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

Decision Tree

In [8]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [9]:
tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
predictions=tree_classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,predictions)
ac=accuracy_score(y_test,predictions)

In [12]:
print(cm)

[[231   5]
 [  3 173]]


In [13]:
print(ac)

0.9805825242718447


KNN

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [22]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [23]:
knn_predict=knn.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,knn_predict)
ac=accuracy_score(y_test,knn_predict)

In [25]:
print(ac)

1.0


In [26]:
print(cm)

[[236   0]
 [  0 176]]


Random Forest Classifier

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [28]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [29]:
y_pred=classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [31]:
print(cm)

[[231   5]
 [  0 176]]


In [32]:
print(ac)

0.9878640776699029
